window.ExportPdf = {
  generate(assessment, templates, statuses, products) {
    const selected = assessment.selected_components || [];
    const rows = selected.map(c => {
      const name = (products.find(p => p.id === c) || {}).name || c;
      const sc = Scoring.scoreFor(templates[c], statuses[c] || {});
      const color = sc.overall > 80 ? '#34c759' : sc.overall >= 60 ? '#ff9f0a' : '#ff3b30';
      return `<tr>
        <td>${name}</td>
        <td style="color:${color};font-weight:600">${sc.overall}%</td>
        <td>${sc.hc}%</td>
        <td>${sc.pu}%</td>
      </tr>`;
    }).join('');

    const overallTotal = selected.reduce((s, c) => s + Scoring.scoreFor(templates[c], statuses[c] || {}).overall, 0);
    const overallAvg = selected.length ? Math.round(overallTotal / selected.length) : 0;
    const overallColor = overallAvg > 80 ? '#34c759' : overallAvg >= 60 ? '#ff9f0a' : '#ff3b30';

    const logo = 'https://www.manageengine.com/images/manageengine-logo-2.svg';
    const date = assessment.assessment_date || new Date().toISOString().slice(0, 10);

    const win = window.open('', '_blank');
    win.document.write(`<!doctype html><html><head><title>HCT Report — ${assessment.customer_name}</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, "Helvetica Neue", Arial, sans-serif; margin: 0; padding: 0; color: #1d1d1f; line-height: 1.5; }
  .page { padding: 48px 56px; max-width: 900px; margin: 0 auto; }
  .cover { padding: 80px 56px; }
  h1 { font-size: 32px; font-weight: 700; margin: 40px 0 8px; }
  h2 { font-size: 22px; font-weight: 600; margin: 32px 0 16px; border-bottom: 1px solid #e5e5ea; padding-bottom: 8px; }
  .meta { color: #6e6e73; font-size: 15px; line-height: 2; }
  .overall { display: inline-block; font-size: 52px; font-weight: 700; color: ${overallColor}; margin: 16px 0; }
  table { width: 100%; border-collapse: collapse; margin: 16px 0; font-size: 14px; }
  th { text-align: left; padding: 10px 12px; background: #f5f5f7; font-weight: 600; color: #1d1d1f; border-bottom: 2px solid #e5e5ea; }
  td { padding: 10px 12px; border-bottom: 1px solid #f0f0f2; }
  tr:last-child td { border-bottom: none; }
  .footer { margin-top: 40px; font-size: 12px; color: #aeaeb2; border-top: 1px solid #e5e5ea; padding-top: 16px; }
  @media print { .page { padding: 36px 40px; } }
</style>
</head><body>
<div class="cover">
  <img src="${logo}" style="height:36px" alt="ManageEngine"/>
  <h1>Health Check &amp; Product Utilization Report</h1>
  <div class="meta">
    <div><strong>Customer:</strong> ${assessment.customer_name}</div>
    <div><strong>Domain:</strong> ${assessment.customer_domain || '—'}</div>
    <div><strong>Assessor:</strong> ${assessment.assessor_name || '—'}</div>
    <div><strong>Date:</strong> ${date}</div>
  </div>
  <div class="overall">${overallAvg}% Overall</div>
</div>

<div class="page">
  <h2>Executive Summary</h2>
  <p style="color:#6e6e73;font-size:15px">Your ManageEngine environment has been assessed across ${selected.length} selected product${selected.length !== 1 ? 's' : ''}. Items scored below 60% require immediate attention. Items between 60–80% should be prioritized in the next review cycle.</p>
  <table>
    <tr><th>Product</th><th>Overall Score</th><th>Health Check (HC)</th><th>Product Utilization (PU)</th></tr>
    ${rows}
  </table>
</div>

<div class="page">
  <h2>Scoring Guide</h2>
  <table>
    <tr><th>Status</th><th>Meaning</th></tr>
    <tr><td><strong>Configured</strong></td><td>Feature is fully deployed and operational</td></tr>
    <tr><td><strong>Partial</strong></td><td>Feature is partly configured or inconsistently applied</td></tr>
    <tr><td><strong>Not Configured</strong></td><td>Feature is not yet deployed — action required</td></tr>
    <tr><td><strong>N/A</strong></td><td>Not applicable to this environment — excluded from score</td></tr>
    <tr><td><strong>Info</strong></td><td>Informational only — excluded from score</td></tr>
  </table>
  <h2>Glossary</h2>
  <table>
    <tr><th>Abbreviation</th><th>Meaning</th></tr>
    <tr><td>HC</td><td>Health Check — measures product configuration and hardening</td></tr>
    <tr><td>PU</td><td>Product Utilization — measures feature adoption</td></tr>
    <tr><td>CIS</td><td>Center for Internet Security Controls v8</td></tr>
    <tr><td>MFA</td><td>Multi-Factor Authentication</td></tr>
    <tr><td>TLS</td><td>Transport Layer Security</td></tr>
    <tr><td>RBAC</td><td>Role-Based Access Control</td></tr>
    <tr><td>DLP</td><td>Data Loss Prevention</td></tr>
    <tr><td>SIEM</td><td>Security Information and Event Management</td></tr>
  </table>
  <div class="footer">Generated by ManageEngine HCT · ${date}</div>
</div>
</body></html>`);
    win.document.close();
    win.focus();
    win.print();
  }
};
