window.ExportPdf={
  generate(assessment,templates,statuses,products){
    const rows=(assessment.selected_components||[]).map(c=>{const name=(products.find(p=>p.id===c)||{}).name||c;return `<tr><td>${name}</td><td>${this.componentScore(c,templates,statuses)}%</td></tr>`;}).join('');
    const win=window.open('','_blank');
    const logo='https://www.manageengine.com/images/manageengine-logo-2.svg';
    win.document.write(`<!doctype html><html><head><title>Report</title><style>body{font-family:Helvetica,Arial,sans-serif;padding:36px;line-height:1.5}h1{font-size:34px;margin:12px 0}table{width:100%;border-collapse:collapse}td,th{border:1px solid #ddd;padding:8px}.page{page-break-after:always}small{color:#666}</style></head><body>
      <section class="page"><img src="${logo}" style="height:42px"/><h1>Health Check & Product Utilization Report</h1><p><b>Customer:</b> ${assessment.customer_name}<br><b>Domain:</b> ${assessment.customer_domain||'—'}<br><b>Assessor:</b> ${assessment.assessor_name||'—'}<br><b>Date:</b> ${assessment.assessment_date||'—'}</p></section>
      <section class="page"><h2>Executive Summary</h2><p>Your environment has been assessed across selected components. Focus first on red-status controls to reduce security and operational exposure.</p><table><tr><th>Component</th><th>Score</th></tr>${rows}</table></section>
      <section><h2>Glossary</h2><p><b>HC</b>: Health Check · <b>PU</b>: Product Utilization · <b>MFA</b>: Multi-factor Authentication · <b>SACL</b>: System Access Control List · <b>FIM</b>: File Integrity Monitoring · <b>DLP</b>: Data Loss Prevention · <b>SIEM</b>: Security Information and Event Management</p><small>Generated by ManageEngine HCT · ${new Date().toISOString().slice(0,10)}</small></section>
      </body></html>`);
    win.document.close();
    win.focus();
    win.print();
  },
  componentScore(c,templates,statuses){const t=templates[c];if(!t)return 0;const W={configured:1,partial:.5,not_configured:0};let n=0,d=0;for(const s of (t.sections||[])){for(const i of (s.criteria||[])){const st=(statuses[c]||{})[i.id];if(!(st in W))continue;d++;n+=W[st];}}return d?Math.round(n/d*100):0;}
};
